### ISSUE TITLE
Caching issue with the obfuscation

### ISSUE THREAD

**Issue by ipragmatechadmin** [JoanZapata/android-asyncservice#10]
There are issues using the caching if someone use obfuscate the project. I used this sample https://github.com/ipragmatech/AsyncService-Spring-Android-Sample and got this error:
 
05-23 17:37:04.571  21114-21129/com.ipragmatech.asyncservice W/AsyncServiceCache﹕ Was unable to store object com.ipragmatech.asyncservice.model.response.UserResponse@425fea60 in cache.
    java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: com.ipragmatech.asyncservice.model.response.UserResponse
            at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.a(Unknown Source)
            at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.a(Unknown Source)
            at com.esotericsoftware.kryo.Kryo.b(Unknown Source)
            at com.esotericsoftware.kryo.Kryo.a(Unknown Source)
            at com.esotericsoftware.kryo.Kryo.c(Unknown Source)
            at com.snappydb.internal.DBImpl.a(Unknown Source)
            at com.joanzapata.android.asyncservice.api.internal.AsyncServiceCache.a(Unknown Source)
            at com.ipragmatech.asyncservice.GithubServiceImpl$3.run(Unknown Source)
            at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$1.a(Unknown Source)
            at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$Task.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.InstantiationException: can't instantiate class com.esotericsoftware.kryo.serializers.FieldSerializer; no empty constructor
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.a(Unknown Source)
            at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.a(Unknown Source)
            at com.esotericsoftware.kryo.Kryo.b(Unknown Source)
            at com.esotericsoftware.kryo.Kryo.a(Unknown Source)
            at com.esotericsoftware.kryo.Kryo.c(Unknown Source)
            at com.snappydb.internal.DBImpl.a(Unknown Source)
            at com.joanzapata.android.asyncservice.api.internal.AsyncServiceCache.a(Unknown Source)
            at com.ipragmatech.asyncservice.GithubServiceImpl$3.run(Unknown Source)
            at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$1.a(Unknown Source)
            at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$Task.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

Can you help me in resolving this issue?

**Comment by JoanZapata** [comment]
Are you saying it works when you disable proguard?

**Comment by ipragmatechadmin** [comment]
Yes, It works fine if minifyEnable is set false. Try to run your example or https://github.com/ipragmatech/AsyncService-Spring-Android-Sample with progruard enabled.

**Comment by ipragmatechadmin** [comment]
Hi Joan,

Finally able to resolve the issue by adding following in the proguard file:

#SnappyDB
-keep class com.esotericsoftware.kryo.** {*;}

I shall update my example as well so the people get the full example with the network.

Cheers,
Kapil

**Comment by JoanZapata** [comment]
Oops, sorry I missed your answer. I added your proguard config to the main page. Thanks!

**Comment by ipragmatechadmin** [comment]
You are welcome :-). I have question regarding Error Handling, I noticed that adding errorManagement on every method handles the exceptions but I couldn't found a way to keep common exception(Like network issue or server Internal error) in Base Class. I tried to put the errorManagement annotation on class as mentioned in your blog but it's not working. Could you help me to find a way where I can keep the common Exception at base class and have special error handing for methods ?

**Comment by JoanZapata** [comment]
Can you open an issue about this a show some example code please? I think what you describe should be working.

**Comment by ipragmatechadmin** [comment]
thx for quick response.  Actually it was fault at my end, I added ErrorManagement in the function to handle special case and could have common errormanagement in the class level :-)
