### ISSUE TITLE
Rejecting re-init on previously-failed class java.lang.Class<com.joanzapata.android.asyncservice.api.internal.AsyncServiceCache>

### ISSUE THREAD

**Issue by virmaninupur5** [JoanZapata/android-asyncservice#14]
Hi ,

Android - asyncservice is working in the my app and I get data response from cache aswell as from service.
But when I tested app on Mi 4i android phone , its is showing below error. This error come in Mi 4i device. I get the response when I don't use  @CacheThenCall on Mi 4i.

Rejecting re-init on previously-failed class java.lang.Class<com.joanzapata.android.asyncservice.api.internal.AsyncServiceCache>
07-30 06:10:21.718  15166-15191/com.ipragmatech.truefriends E/Truefriends﹕ Handing exception in mappercom.joanzapata.android.asyncservice.api.internal.AsyncServiceCache
    java.lang.UnsatisfiedLinkError: com.joanzapata.android.asyncservice.api.internal.AsyncServiceCache
            at com.ipragmatech.socialengineapi.service.SignupServiceImpl$5.run(SignupServiceImpl.java:225)
            at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$1.execute(BackgroundExecutor.java:106)
            at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$Task.run(BackgroundExecutor.java:266)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by ipragmatechadmin** [comment]
I think upgrading snappyDB to 0.5.2 should resolve this issue.

**Comment by JoanZapata** [comment]
Will do on next release, thanks @ipragmatechadmin

**Comment by rjain90** [comment]
Has this issue been resolved yet?

**Comment by ipragmatechadmin** [comment]
Yes, the issue was resolved and you need to upgrade SnappyDB to latest version.

**Comment by rjain90** [comment]
I'm trying to do that by doing the following:

```
 compile('com.joanzapata.android.asyncservice:android-asyncservice:0.0.5@aar') {
        transitive = true
        exclude group: 'com.snappydb'
    }
    compile 'com.snappydb:snappydb-lib:0.4.0'
    compile 'com.esotericsoftware.kryo:kryo:2.24.0'
```

But I keep getting the error:

```
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi/libsnappydb-native.so
    File1: /Users/rishabhjain/Documents/workspace/Viuby/app/build/intermediates/exploded-aar/com.joanzapata.android.asyncservice/android-asyncservice/0.0.5/jni
    File2: /Users/rishabhjain/Documents/workspace/Viuby/app/build/intermediates/exploded-aar/com.snappydb/snappydb-lib/0.4.0/jni
```

Please suggest how to solve this.

**Comment by ipragmatechadmin** [comment]
We resolved it by importing the Async project in our project and added 

```
compile ('com.snappydb:snappydb-lib:0.5.2')
compile 'com.esotericsoftware.kryo:kryo:2.24.0'
compile 'com.joanzapata.android.asyncservice:android-asyncservice-processors:0.0.5'
compile 'com.joanzapata.android.asyncservice:android-asyncservice-api:0.0.5'
```
