### ISSUE TITLE
java.lang.NullPointerException on compilation

### ISSUE THREAD

**Issue by ionutandone** [JoanZapata/android-asyncservice#16]
So the library fails when I try to compile my project. I think I know what's the problem but I also think that you should explicitly state the limitation of your library in the README.

```
15:19:54.228 [ERROR] [org.gradle.BuildExceptionReporter] 
15:19:54.230 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:19:54.230 [ERROR] [org.gradle.BuildExceptionReporter] 
15:19:54.231 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:19:54.231 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':menthal:compileDebugJavaWithJavac'.
15:19:54.231 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException
15:19:54.232 [ERROR] [org.gradle.BuildExceptionReporter] 
15:19:54.232 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:19:54.233 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':menthal:compileDebugJavaWithJavac'.
15:19:54.233 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:19:54.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:19:54.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:19:54.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
15:19:54.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:19:54.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
15:19:54.235 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:19:54.235 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:19:54.235 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:19:54.236 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
15:19:54.236 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
15:19:54.236 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
15:19:54.237 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
15:19:54.237 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
15:19:54.237 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
15:19:54.238 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
15:19:54.238 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:19:54.238 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
15:19:54.238 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
15:19:54.239 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:19:54.239 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:19:54.239 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
15:19:54.240 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
15:19:54.240 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
15:19:54.240 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
15:19:54.240 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
15:19:54.241 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
15:19:54.241 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
15:19:54.241 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
15:19:54.241 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
15:19:54.241 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
15:19:54.242 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
15:19:54.242 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
15:19:54.242 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
15:19:54.242 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
15:19:54.242 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:19:54.243 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
15:19:54.243 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
15:19:54.244 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:19:54.244 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:19:54.244 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
15:19:54.244 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:19:54.245 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
15:19:54.245 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
15:19:54.245 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:19:54.245 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
15:19:54.245 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
15:19:54.245 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
15:19:54.246 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.NullPointerException
15:19:54.246 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.Main.compile(Main.java:553)
15:19:54.246 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
15:19:54.246 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
15:19:54.246 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:42)
15:19:54.247 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
15:19:54.247 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
15:19:54.247 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
15:19:54.247 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
15:19:54.247 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
15:19:54.248 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
15:19:54.248 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
15:19:54.248 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
15:19:54.248 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:92)
15:19:54.248 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
15:19:54.249 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
15:19:54.249 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
15:19:54.249 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
15:19:54.249 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
15:19:54.249 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:19:54.250 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:19:54.250 [ERROR] [org.gradle.BuildExceptionReporter]        ... 47 more
15:19:54.250 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
15:19:54.250 [ERROR] [org.gradle.BuildExceptionReporter]        at com.joanzapata.android.asyncservice.processors.utils.Utils.hasTypeParameters(Utils.java:236)
15:19:54.250 [ERROR] [org.gradle.BuildExceptionReporter]        at com.joanzapata.android.asyncservice.processors.AsyncServiceAP.createDelegateMethod(AsyncServiceAP.java:255)
15:19:54.251 [ERROR] [org.gradle.BuildExceptionReporter]        at com.joanzapata.android.asyncservice.processors.AsyncServiceAP.process(AsyncServiceAP.java:158)
15:19:54.251 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
15:19:54.251 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
15:19:54.251 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
15:19:54.251 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
15:19:54.251 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
15:19:54.252 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
15:19:54.252 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
15:19:54.252 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.Main.compile(Main.java:523)
15:19:54.252 [ERROR] [org.gradle.BuildExceptionReporter]        ... 66 more
15:19:54.252 [ERROR] [org.gradle.BuildExceptionReporter] 
```

**Comment by ionutandone** [comment]
The demo doesn't work for me. 
`java.lang.NullPointerException
            at org.menthal.myapplication.MainActivity$1.onClick(MainActivity.java:36)`

This happens when I try to call a method in the asynservice. The application is exactly like the demo.
