### ISSUE TITLE
NoClassDefFoundError with jtds

### ISSUE THREAD

**Issue by htekgulds** [JoanZapata/android-asyncservice#7]
Hello,
I'm having a ClassNotFound exception when I try to use jtds in an AsyncService, which works fine inside an AsyncTask. The code thats failing is:
```
Class.forName("net.sourceforge.jtds.jdbc.Driver").newInstance();
```
Could you help me figure out why, please? Any help would be appreciated. Thanks in advance. Following is the logcat im getting: 

```
03-05 23:09:15.259    5340-5395/com.htds.mobilesales W/System.err﹕ java.lang.ClassNotFoundException: net.sourceforge.jtds.jdbc.Driver
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.Class.classForName(Native Method)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.Class.forName(Class.java:308)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.Class.forName(Class.java:272)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at com.htds.datalayer.util.ConnectionUtil.test(ConnectionUtil.java:53)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at com.htds.mobilesales.service.async.SetupService.savePrefs(SetupService.java:23)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at com.htds.mobilesales.service.async.SetupServiceImpl.access$001(SetupServiceImpl.java:15)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at com.htds.mobilesales.service.async.SetupServiceImpl$1.run(SetupServiceImpl.java:34)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$1.execute(BackgroundExecutor.java:106)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at com.joanzapata.android.asyncservice.api.internal.BackgroundExecutor$Task.run(BackgroundExecutor.java:266)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-05 23:09:15.260    5340-5395/com.htds.mobilesales W/System.err﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
03-05 23:09:15.275    5340-5395/com.htds.mobilesales W/System.err﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
03-05 23:09:15.275    5340-5395/com.htds.mobilesales W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-05 23:09:15.276    5340-5395/com.htds.mobilesales W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-05 23:09:15.276    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
03-05 23:09:15.276    5340-5395/com.htds.mobilesales W/System.err﹕ Caused by: java.lang.ClassNotFoundException: Didn't find class "net.sourceforge.jtds.jdbc.Driver" on path: DexPathList[[zip file "/data/app/com.htds.mobilesales-1/base.apk"],nativeLibraryDirectories=[/data/app/com.htds.mobilesales-1/lib/arm, /vendor/lib, /system/lib]]
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ ... 16 more
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ Suppressed: java.lang.ClassNotFoundException: net.sourceforge.jtds.jdbc.Driver
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.Class.classForName(Native Method)
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-05 23:09:15.281    5340-5395/com.htds.mobilesales W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-05 23:09:15.282    5340-5395/com.htds.mobilesales W/System.err﹕ ... 17 more
03-05 23:09:15.282    5340-5395/com.htds.mobilesales W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by JoanZapata** [comment]
Do you use proguard?

**Comment by htekgulds** [comment]
No I think I don't. In any case here's my build.gradle: 
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion '21.1.2'

    defaultConfig {
        applicationId "com.htds.mobilesales"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}

repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url 'http://raw.github.com/wada811/Android-Material-Design-Colors/master/repository/' }
    mavenCentral()
}

dependencies {
    compile project(':datalayer')
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:cardview-v7:21.0.3'
    compile 'com.android.support:recyclerview-v7:21.0.3'

    provided 'org.roboguice:roboblender:3.0.1'
    compile 'org.roboguice:roboguice:3.0.1'
    compile 'com.nispok:snackbar:2.10.1'

    // TODO: GİDECEK
    compile 'org.lucasr.twowayview:core:1.0.0-SNAPSHOT@aar'
    compile 'org.lucasr.twowayview:layouts:1.0.0-SNAPSHOT@aar'
    // TODO: GİDECEK

    compile 'com.pnikosis:materialish-progress:1.0'
    compile 'com.rengwuxian.materialedittext:library:1.8.2'
    compile 'com.getbase:floatingactionbutton:1.3.0'
    compile 'at.wada811:android-material-design-colors:1.1.0'
    compile 'me.dm7.barcodescanner:zxing:1.6'
    compile 'me.drakeet.materialdialog:library:1.2.2'
    compile('com.mikepenz.materialdrawer:library:1.0.2@aar') { transitive = true }
    compile 'com.mikepenz.iconics:library:0.7.5@aar'
    compile 'com.mikepenz.iconics:meteocons-typeface:1.1.1@aar'
    compile('com.joanzapata.android.asyncservice:android-asyncservice:0.0.5@aar') { transitive = true }
}
```

And proguard-rules.pro:

```
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in D:\Programlar\sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}
```

And my service:
```java
@AsyncService
public class SetupService {

    public Result savePrefs(Context context, String ip, String db, String user, String pass) {
        if (ip.equals("") || db.equals("") || user.equals("") || pass.equals("")) {
            return Result.INVALID;
        }
        if (!ConnectionUtil.test(ip, db, user, pass)) {
            return Result.FAIL;
        }

    ...
}
```
Here, the code inside ConnectionUtil.test() gives the error:

```
public static boolean test(String ip, String db, String user, String pass) {

        String url = DRIVER + ip + "/" + db;

        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement statement = conn.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }
```

**Comment by htekgulds** [comment]
Solved the issue. It was my mistake actually. The jtds.jar file was under the libs of my app module and it worked fine but when I changed the code to use AsyncService I needed to put the jar file under the db module, which actually hosts the ConnectionUtil class. Sorry for the fuss
